### ISSUE TITLE
Popup closes directly

### ISSUE THREAD

**Issue by ducedo** [MHDante/HabitRPG-SitePass#1]
Whenever I click on "Block site!", edit or delete - the popup jumps up (I believe there's a input field) but closes before I'm able to see or do anything. First I thought it was due to AdBlock but nothing changed when I disabled it. Then I changed the chrome settings to allow popups from all sites, but no result.

The popup saying "It will cost you 0.00 to access" works.

I've tried to reinstall the plugin and restart Chrome several times without result.

Edit: When I restart the browser, all the sites I saved disappears. Not sure if it could be some problem with saving the data or it's due to me not seeing and clicking in the popup.

**Comment by MHDante** [comment]
Ah. I guess it just worked for me. This is related to to this chrome issue:

https://code.google.com/p/chromium/issues/detail?id=29379

I'll post an updated build in the next few days.

**Comment by MHDante** [comment]
I've updated the UI to prevent the Issue mentioned here. Let me know if it worked!

**Comment by ducedo** [comment]
Thanks, now it works perfectly.

**Comment by MHDante** [comment]
Sweet! This is my first bug report ever, Thank you very much!
